# GitHub 저장소용 label 정의
# 사용법: gh label create <name> --color <color> --description <description>

# 기본 PR 타입
- name: enhancement
  color: "0366d6"
  description: "새로운 기능이나 개선사항"

- name: bug
  color: "d73a4a"
  description: "버그 수정"

- name: documentation
  color: "0075ca"
  description: "문서 수정 또는 추가"

- name: testing
  color: "c2e0c6"
  description: "테스트 코드 추가 또는 수정"

- name: maintenance
  color: "fef2c0"
  description: "유지보수 작업"

- name: security
  color: "ff0000"
  description: "보안 관련 수정"

- name: dependencies
  color: "0366d6"
  description: "의존성 업데이트"

- name: breaking-change
  color: "ff0000"
  description: "호환성을 깨뜨리는 변경사항"

# 새로운 label들
- name: revert
  color: "d73a4a"
  description: "변경사항 되돌리기"

- name: types
  color: "0075ca"
  description: "타입 정의 또는 수정"

- name: accessibility
  color: "7057ff"
  description: "접근성 개선"

- name: i18n
  color: "008672"
  description: "국제화 관련"

- name: mobile
  color: "fbca04"
  description: "모바일 관련 변경사항"

- name: desktop
  color: "0366d6"
  description: "데스크톱 관련 변경사항"

- name: web
  color: "0075ca"
  description: "웹 관련 변경사항"

# PR 크기별 label
- name: size-XS
  color: "00ff00"
  description: "매우 작은 변경사항 (10줄 이하)"

- name: size-S
  color: "7c1158"
  description: "작은 변경사항 (11-30줄)"

- name: size-M
  color: "5319e7"
  description: "중간 변경사항 (31-100줄)"

- name: size-L
  color: "fbca04"
  description: "큰 변경사항 (101-500줄)"

- name: size-XL
  color: "ff0000"
  description: "매우 큰 변경사항 (500줄 초과)"

# 우선순위 label
- name: high-priority
  color: "ff0000"
  description: "높은 우선순위"

- name: medium-priority
  color: "ffa500"
  description: "중간 우선순위"

- name: low-priority
  color: "00ff00"
  description: "낮은 우선순위"

# 상태 label
- name: in-progress
  color: "fef2c0"
  description: "진행 중"

- name: ready-for-review
  color: "0366d6"
  description: "리뷰 준비 완료"

- name: needs-review
  color: "ffa500"
  description: "리뷰 필요"

- name: approved
  color: "00ff00"
  description: "승인됨"

# 기타 label
- name: good-first-issue
  color: "7057ff"
  description: "초보자에게 좋은 이슈"

- name: help-wanted
  color: "008672"
  description: "도움 필요"

- name: wont-fix
  color: "ffffff"
  description: "수정하지 않을 예정"

- name: duplicate
  color: "cfd3d7"
  description: "중복된 이슈"

- name: invalid
  color: "e4e669"
  description: "유효하지 않은 이슈"
